# Change these first
owner: phante # Your GitHub organization or username, where this repository lives
repo: prdi-status # The name of this repository

sites:
  - name: progettodighe
    url: https://www.progettodighe.it
  - name: umami.progettodighe
    url: https://umami.progettodighe.it
  - name: vajont.eu
    url: https://vajont.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.prdi.it
  # baseUrl: /prdi-status
  logoUrl: https://progettodighe.it/asset/brand/PDLogo.svg
  name: ProgettoDighe Status Site
  introTitle: ""
  introMessage: "" 
  navbar:
    - title: Home
      href: https://prdi.it
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
